#include <stdio.h>
int main()
{
    int x,cnt=1;
    scanf("%d",&x);
    printf("Hailstone generated by %d:\n",x);
    printf("%4d",x);
    while(x!=1)
    {
        if(x%2==0)
        {
            x/=2;
            cnt++;
            printf("%4d",x);
        }
        else
        {
            x=3*x+1;
            cnt++;
            printf("%4d",x);
        }
        if(cnt%6==0) printf("\n");
    }
    if(cnt%6==0)
        printf("Number of hailstone generated:%d\n",cnt);
    else
        printf("\nNumber of hailstone generated:%d\n",cnt);
    return 0;
}
